name: Build Geode Mod

on:
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        config:
        - name: Cospylet platform
          os: windows-latest

        - name: Android 64/2
          os: ubuntu-latest
          target: Android32

        - name: Android64 my beloved
          os: ubuntu-latest
          target: Android64

        - name: MacOS for the -4 users
          os: macos-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
      
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
